### ISSUE TITLE
circular reference error

### ISSUE THREAD

**Issue by gym15142027759** [esa/dSGP4#13] opened 2024-07-17 08:08 UTC
Why does python prompt a circular reference error and how to resolve it?
![Uploading 1721203646613.jpg…]()

**Comment by Sceki** [comment] 2024-07-17 08:34
@gym15142027759 the image you shared is not visible.. do you mind sending the error again?

**Comment by gym15142027759** [comment] 2024-07-17 08:59
Dear Acciarini：

Apologies for the inconvenience caused earlier. I have now re-attached the image with the circular reference error you requested. Please find it attached to this email.

I hope this provides the clarity you need. If you require any further assistance, please do not hesitate to let me know.

The problem is " ImportError: cannot import name 'torch type' from partially initialized module 'dsgp4'(most likely due circular import)(c:\Users\86135\anaconda3\eto a nvs\pythonProject4\lib\site-packages\dsgp4\init .py)"

Best regards, gym15142027759













At 2024-07-17 15:34:23, "Giacomo Acciarini" ***@***.***> wrote:

@gym15142027759 the image you shared is not visible.. do you mind sending the error again?

**Comment by Sceki** [comment] 2024-07-17 10:01
Can you please tell me what is the code that triggers this error?

**Comment by Sceki** [comment] 2024-07-17 10:47
I cannot reproduce your error when importing the module, and the tests run fine (see also CI/CD).

I think you might have some problems in your local environment, but I am not entirely sure since I do not know what triggered the above.

In any case, I would recommend you create a new conda environment from scratch, and then you do `conda install dsgp4` there. Then, try to use `dsgp4`: you should not see any problems, but let me know if that is not the case.

**Comment by gym15142027759** [comment] 2024-07-17 10:50
Thank you, I will try it again,in a new environment.

Best wishes!













At 2024-07-17 17:47:53, "Giacomo Acciarini" ***@***.***> wrote:

I cannot reproduce your error when importing the module, and the tests run fine (see also CI/CD).

I think you might have some problems in your local environment, but I am not entirely sure since I do not know what triggered the above.

In any case, I would recommend you create a new conda environment from scratch, and then you do conda install dsgp4 there. Then, try to use dsgp4: you should not see any problems, but let me know if that is not the case.

**Comment by Sceki** [comment] 2024-07-17 11:21
I will close this for now. Let me know if you have issues and we can re-open this issue

**Closed by Sceki** 2024-07-17 11:21 UTC

**Comment by gym15142027759** [comment] 2024-07-19 04:50
I am very sorry that I found that there is still a reference problem in my code, and I have looked at the code and found that there is indeed a circular reference in your code. 

The following is the error when I imported dsgp4：

ImportError: cannot import name 'torch_type' from partially initialized module 'dsgp4' (most likely due to a circular import) (C:\Users\86135\anaconda3\envs\pythonProject4\lib\site-packages\dsgp4\__init__.py)
















At 2024-07-17 15:34:23, "Giacomo Acciarini" ***@***.***> wrote:

@gym15142027759 the image you shared is not visible.. do you mind sending the error again?

**Comment by Sceki** [comment] 2024-07-19 05:05
Hi @gym15142027759 ,

can you please write here exactly the steps to do to reproduce this? You can just paste a snippet of Python code to reproduce the error - otherwise it is not possible for me to understand what is going on.

**Comment by Sceki** [comment] 2024-07-19 05:08
Also: please create a new conda environment, conda install dsgp4, and then try to reproduce this. It might be pythonProject4 environment the issue

**Comment by gym15142027759** [comment] 2024-07-19 05:15
Step 1 : Create a new project pythonProject1

Step 2 : pip install dsgp4

Step 3 : import dsgp4 

A new environment has been built and installed by means of pip




But the step 3 goes wrong,  ImportError

ImportError: cannot import name 'torch_type' from partially initialized module 'dsgp4' 

(most likely due to a circular import) (C:\Users\86135\anaconda3\envs\pythonProject1\lib\site-packages\dsgp4\__init__.py)
















At 2024-07-19 12:06:17, "Giacomo Acciarini" ***@***.***> wrote:

Hi @gym15142027759 ,

can you please write here exactly the steps to do to reproduce this? You can just paste a snippet of Python code to reproduce the error - otherwise it is not possible for me to understand what is going on.

**Comment by Sceki** [comment] 2024-07-19 05:28
Can you please only use conda?

so:
`conda create —name test_installation`
`conda activate test_installation`
`conda install dsgp4 `

and then try to import again

**Comment by gym15142027759** [comment] 2024-07-19 05:30
OK ,I will try it again,at the same time ,I found that :,ax.legend()  also has problems










At 2024-07-19 12:29:13, "Giacomo Acciarini" ***@***.***> wrote:

Can you please only use conda?

so:
conda create —name test_installation
conda activate test_installation
conda install dsgp4

and then try to import again

**Comment by Sceki** [comment] 2024-07-19 05:34
Mixing pip and conda might cause issues: it is best to avoid that: https://www.anaconda.com/blog/using-pip-in-a-conda-environment

that’s why I am suggesting to only use conda first

**Comment by gym15142027759** [comment] 2024-07-19 05:41
OK thank you ,I will try it by anaconda 
















At 2024-07-19 12:34:33, "Giacomo Acciarini" ***@***.***> wrote:

Mixing pip and conda might cause issues: it is best to avoid that: https://www.anaconda.com/blog/using-pip-in-a-conda-environment

that’s why I am suggesting to only use conda first
